spring:
  profiles:
    active: local

  application:
    name: biz-core-template

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:33077/nct?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: root
      password: 1234
      minimum-idle: 10
      maximum-pool-size: 10

  data:
    redis:
      host: localhost
      port: 63799
      password:

    mongodb:
      host: localhost
      port: 27027

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    hikari:
      driver-class-name:
      jdbc-url:
      username:
      password:
      minimum-idle: 10
      maximum-pool-size: 10

  data:
    redis:
      host:
      port:
      password:

  jpa:
    database-platform:
    hibernate:
      ddl-auto: