spring:
  profiles:
    active: local

  application:
    name: biz-core-template

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://192.168.10.42:65001/nct?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: root
      password: 1234
      minimum-idle: 10
      maximum-pool-size: 10

  data:
    mongodb:
      uri: mongodb://192.168.10.42:65002
      database: nct
      min-idle: 10
      max-size: 10

    redis:
      host: 192.168.10.42
      port: 65003
      password:
      lettuce:
        pool:
          max-idle: 8
          min-idle: 8

  jpa:
    hibernate:
      ddl-auto: create

  session:
    redis:
      repository-type: indexed
      namespace: spring

server:
  servlet:
    session:
      cookie:
        name: JSESSIONID
        path: /
        domain: localhost
        http-only: false
        secure: false
      timeout: 3600

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    hikari:
      driver-class-name:
      jdbc-url:
      username:
      password:
      minimum-idle: 10
      maximum-pool-size: 10

  data:
    mongodb:
      uri:
      database:
      min-idle: 10
      max-size: 10

    redis:
      host:
      port:
      password:
      lettuce:
        pool:
          max-idle: 8
          min-idle: 8

  jpa:
    hibernate:
      ddl-auto: create

  session:
    redis:
      repository-type: indexed
      namespace: spring

server:
  servlet:
    session:
      cookie:
        name: JSESSIONID
        path: /
        domain:
        http-only:
        secure:
      timeout: