spring:
  profiles:
    active: local

  application:
    name: biz-core-template

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:65001/nct?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: root
      password: 1234
      minimum-idle: 10
      maximum-pool-size: 10

  data:
    mongodb:
      uri: mongodb://localhost:65002
      database: nct

    redis:
      host: localhost
      port: 65003
      password:

  jpa:
#    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create

  session:
    redis:
      repository-type: indexed
      namespace: spring

server:
  servlet:
    session:
      cookie:
        name: JSESSIONID
        path: /
        domain: localhost
        http-only: false
        secure: false
      timeout: 3600

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    hikari:
      driver-class-name:
      jdbc-url:
      username:
      password:
      minimum-idle: 10
      maximum-pool-size: 10

  data:
    redis:
      host:
      port:
      password:

  jpa:
    database-platform:
    hibernate:
      ddl-auto:

server:
  servlet:
    session:
      cookie:
        name:
        path:
        domain:
        http-only:
        secure:
      timeout: